import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Suspense } from 'react'
import { YandexMetrika } from '../entities/yandex-metrika'
import { Header } from '@repo/ui/components/header'
import { Main } from '@repo/ui/components/main'
import { Footer } from '@repo/ui/components/footer'
import { Copyright } from '@repo/ui/components/copyright'
import { APP_NAME } from '../shared/constants'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header>header</Header>
        <Main>
          {children}
          <Suspense>
            <YandexMetrika />
          </Suspense>
        </Main>
        <Footer>
          <Copyright name={APP_NAME} />
        </Footer>
      </body>
    </html>
  )
}
