import 'server-only'

import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Suspense } from 'react'
// import { Copyright } from '@repo/ui/components/copyright'
import { ThemeProvider } from '@repo/ui/providers/theme-provider'
import { Header } from '@repo/ui/components/tags/header'
import { Main } from '@repo/ui/components/tags/main'
import { Footer } from '@repo/ui/components/tags/footer'
import { YandexMetrika } from '@/shared/yandex-metrika'
// import { APP_NAME } from '@/shared/constants'
import { StoreProvider } from '@/app/store'
import { exampleSlice } from '@/entities/example/store'
import { example2Slice } from '@/entities/example2/store'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider slices={[exampleSlice, example2Slice]}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange>
            <Header>header</Header>
            <Main>{children}</Main>
            <Footer>{/* <Copyright name={APP_NAME} /> */}</Footer>
          </ThemeProvider>
          <Suspense>
            <YandexMetrika />
          </Suspense>
        </StoreProvider>
      </body>
    </html>
  )
}
