import 'server-only'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Suspense } from 'react'
import { YandexMetrika } from '../entities/yandex-metrika'
import { Copyright } from '@repo/ui/components/copyright'
import { APP_NAME } from '../shared/constants'
import { ThemeProvider } from '@repo/ui/providers/theme-provider'
import { Header } from '@repo/ui/tags/header'
import { Main } from '@repo/ui/tags/main'
import { Footer } from '@repo/ui/tags/footer'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Header>header</Header>
          <Main>{children}</Main>
          <Footer>
            <Copyright name={APP_NAME} />
          </Footer>
        </ThemeProvider>
        <Suspense>
          <YandexMetrika />
        </Suspense>
      </body>
    </html>
  )
}
