import 'server-only'

import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Suspense } from 'react'
import { Copyright } from '@repo/ui/components/copyright'
import { Header } from '@repo/ui/components/tags/header'
import { Main } from '@repo/ui/components/tags/main'
import { Footer } from '@repo/ui/components/tags/footer'
import { ModeToggle } from '@repo/ui/components/mode-toggle'
import { ThemeProvider } from '@repo/ui/providers/theme-provider'
import { UTMs } from '@repo/next-utms'
import { YandexMetrika } from '@/shared/yandex-metrika'
import { APP_NAME } from '@/shared/constants'
import { StoreProvider } from '@/app/_store'
import { Container } from '@/shared/components/container'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange>
            <div className='p-[1.6rem]'>
              <Container>
                <Header>
                  <ModeToggle />
                </Header>
                <Main>{children}</Main>
                <Footer>
                  <Copyright name={APP_NAME} />
                </Footer>
              </Container>
            </div>
          </ThemeProvider>
          <Suspense>
            <UTMs />
            <YandexMetrika />
          </Suspense>
        </StoreProvider>
      </body>
    </html>
  )
}
