import 'server-only'

import './globals.css'
import type { Metadata } from 'next'
// import localFont from 'next/font/local'
import { Poppins, Lato } from 'next/font/google'
import { Suspense } from 'react'
import { YandexMetrika } from '@/shared/yandex-metrika'
import { Container } from '@/shared/components/container'
import { StoreProvider } from '@/app/store'
import { leadSlice } from '@/entities/lead/store'
import { Footer } from '@/widgets/Footer'
import { NavMenu } from '@/shared/components/nav-menu'
import { cn } from '@/shared/utils'
import { Header } from '@/shared/components/header'
import { Main } from '@/shared/components/main'
import { ThemeProvider } from '@/shared/components/theme-provider'
import { ModeToggle } from '@/shared/components/mode-toggle'
import { UTMs } from '@/shared/components/utms'
import { SWRConfig } from '@/shared/api'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
// })

const poppinsFont = Poppins({
  subsets: ['latin-ext'],
  weight: ['400', '500', '700'],
  variable: '--font-poppins',
  style: 'normal',
  display: 'swap',
  preload: true,
  fallback: [
    'system-ui',
    'ui-sans-serif',
    '-apple-system',
    'BlinkMacMacSystemFont',
    'Segoe UI',
    'arial',
    'Roboto',
    'Ubuntu',
    'sans-serif',
  ],
  adjustFontFallback: true,
})

const latoFont = Lato({
  subsets: ['latin-ext'],
  weight: ['400'],
  variable: '--font-lato',
  style: 'normal',
  display: 'swap',
  preload: true,
  fallback: [
    'system-ui',
    'ui-sans-serif',
    '-apple-system',
    'BlinkMacMacSystemFont',
    'Segoe UI',
    'arial',
    'Roboto',
    'Ubuntu',
    'sans-serif',
  ],
  adjustFontFallback: true,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          poppinsFont.variable,
          latoFont.variable,
          'antialiased p-5 font-poppins min-h-dvh',
        )}>
        <StoreProvider slices={[leadSlice]}>
          <SWRConfig>
            <ThemeProvider>
              <Container className='min-h-dvh'>
                <Header>
                  <ModeToggle />
                </Header>
                <Main>{children}</Main>
                <Footer />
              </Container>
              <NavMenu />
            </ThemeProvider>
            <Suspense>
              <UTMs />
              <YandexMetrika />
            </Suspense>
          </SWRConfig>
        </StoreProvider>
      </body>
    </html>
  )
}
