import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Html } from '@repo/ui/components/tags/html'
import { Body } from '@repo/ui/components/tags/body'
import { Main } from '@repo/ui/components/tags/main'
import { StoreProvider } from './_/store/provider'
import { SWRConfig } from '@/shared/api'
import { ThemeProvider } from '@/shared/components/theme-provider'
import { Toaster } from '@/shared/components/sonner'
import { NextLoader } from '@/shared/components/next-topbar'
import { Header } from '@/widgets/header'
import { Suspense } from 'react'
import { Div } from '@repo/ui/components/tags/div'
import { DragNDropProvder } from '@/shared/components/drag-n-drop'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <Html lang='ru'>
      <Body className={`${geistSans.variable} ${geistMono.variable} `}>
        <StoreProvider>
          <SWRConfig>
            <ThemeProvider>
              <DragNDropProvder>
                <Div className='flex flex-col min-h-dvh'>
                  <Suspense>
                    <Header />
                  </Suspense>
                  <Main className='flex flex-col flex-1'>{children}</Main>
                </Div>
              </DragNDropProvder>
              <Toaster />
              <NextLoader />
            </ThemeProvider>
          </SWRConfig>
        </StoreProvider>
      </Body>
    </Html>
  )
}
